import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

const data = [
  { name: 'Spring boot' },
  { name: 'Hibernate' },
  { name: 'Apache Struts' },
  { name: 'Apache Wicket' },
  { name: 'Java' },
  { name: 'Grails' },
  { name: 'Vaadin' },
  { name: 'Micronaut' },
  { name: 'Quarkus' },
  { name: 'Express' },
  { name: 'Nestjs' },
  { name: 'Fastify' },
  { name: 'Koajs' },
  { name: 'Sailsjs' },
  { name: 'LoopBack' },
  { name: 'Hapijs' },
  { name: 'AdonisJS' },
  { name: 'Nextjs' },
  { name: 'Angular' },
  { name: 'Reactjs' },
  { name: 'Vite' },
  { name: 'Django' },
  { name: 'Pyramid' },
  { name: 'TurboGears' },
  { name: 'Bottle' },
  { name: 'CherryPy' },
  { name: 'Tornado' },
  { name: 'FastAPI' },
  { name: 'Sanic' },
  { name: 'React-native' },
  { name: 'Symfony' },
  { name: 'Yii' },
  { name: 'Laminas' },
  { name: 'Phalcon' },
  { name: 'CakePHP' },
  { name: 'Slim' },
  { name: 'Lumen' },
  { name: 'Phalcon' },
  { name: 'ASP.NET' },
  { name: 'Entity Framework' },
  { name: 'NancyFX' },
  { name: 'Akka.NET' },
  { name: 'Gin' },
  { name: 'Echo' },
  { name: 'Beego' },
  { name: 'Revel' },
  { name: 'Fiber' },
  { name: 'Buffalo' },
  { name: 'Iris' },
  { name: 'Gorilla' },
  { name: 'Flutter' },
  { name: 'AngularDart' },
  { name: 'Aqueduct' },
  { name: 'Redstone' },
  { name: 'Angel' },
  { name: 'JavaScript' },
  { name: 'TypeScript' },
  { name: 'Python' },
  { name: 'C#' },
  { name: 'C++' },
  { name: 'Swift' },
  { name: 'Kotlin' },
  { name: 'Go' },
  { name: 'Ruby' },
  { name: 'PHP' },
  { name: 'Rust' },
  { name: 'Dart' },
  { name: 'Scala' },
  { name: 'Lua' },
  { name: 'Perl' },
  { name: 'HTML/CSS' },
  { name: 'Vuejs' },
  { name: 'Ruby on Rails' },
  { name: 'Flask' },
  { name: 'Laravel' },
  { name: 'Symfony ' },
  { name: 'Xamarin' },
  { name: 'MongoDB' },
  { name: 'MySQL' },
  { name: 'PostgreSQL' },
  { name: 'SQLite' },
  { name: 'Redis' },
  { name: 'Oracle Database' },
  { name: 'MariaDB' },
  { name: 'Cassandra' },
  { name: 'Firebase' },
  { name: 'Git' },
  { name: 'GitHub' },
  { name: 'GitLab' },
  { name: 'Docker' },
  { name: 'Kubernetes' },
  { name: 'Jenkins' },
  { name: 'Travis CI' },
  { name: 'AWS' },
  { name: 'Sass' },
  { name: 'JUnit' },
  { name: 'Jest' },
  { name: 'Vitest' },
  { name: 'Pytest' },
  { name: 'PHPUnit' },
  { name: 'Selenium' },
  { name: 'Cucumber' },
  { name: 'Jasmine' },
]

async function main() {
  await Promise.all(
    data.map(
      async (item) =>
        await prisma.technology.upsert({
          where: {
            name: item.name,
          },
          update: {},
          create: {
            name: item.name,
          },
        }),
    ),
  )
}
main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
